package config

import (
	"strings"
	"testing"
)

func TestRenderConfigIni_PreservesCommentsAndOrder(t *testing.T) {
	original := strings.Split(`# Generated by Android Studio
avd.ini.encoding=UTF-8
hw.ramSize=4096

# GPU settings
hw.gpu.mode=auto
tag.id=google_apis
`, "\n")

	kv := map[string]string{
		"avd.ini.encoding": "UTF-8",
		"hw.ramSize":       "1024",
		"hw.gpu.mode":      "host",
		"tag.id":           "google_apis",
	}

	got := renderConfigIni(original, kv)

	// Comments and blank lines survive; the old map-rebuild deleted them.
	for _, want := range []string{"# Generated by Android Studio", "# GPU settings"} {
		if !strings.Contains(got, want) {
			t.Errorf("output lost comment %q\ngot:\n%s", want, got)
		}
	}
	// Updated values applied in place.
	if !strings.Contains(got, "hw.ramSize=1024") {
		t.Errorf("hw.ramSize not updated\ngot:\n%s", got)
	}
	if strings.Contains(got, "hw.ramSize=4096") {
		t.Errorf("old hw.ramSize value still present\ngot:\n%s", got)
	}
	if !strings.Contains(got, "hw.gpu.mode=host") {
		t.Errorf("hw.gpu.mode not updated\ngot:\n%s", got)
	}
	// Original relative order is retained.
	if strings.Index(got, "avd.ini.encoding") > strings.Index(got, "hw.ramSize") {
		t.Error("original key order was not preserved")
	}
	// No key is emitted twice.
	if strings.Count(got, "hw.ramSize=") != 1 {
		t.Errorf("hw.ramSize emitted %d times, want 1", strings.Count(got, "hw.ramSize="))
	}
}

func TestRenderConfigIni_AppendsNewKeysSorted(t *testing.T) {
	original := strings.Split("hw.ramSize=4096\n", "\n")
	kv := map[string]string{
		"hw.ramSize":     "1024",
		"vm.heapSize":    "256",
		"hw.camera.back": "none",
		"hw.dPad":        "no",
	}

	got := renderConfigIni(original, kv)

	for _, want := range []string{"vm.heapSize=256", "hw.camera.back=none", "hw.dPad=no"} {
		if !strings.Contains(got, want) {
			t.Errorf("missing appended key %q\ngot:\n%s", want, got)
		}
	}
	// Appended keys are sorted, so output is stable across runs despite Go's
	// randomised map iteration.
	backIdx := strings.Index(got, "hw.camera.back")
	dpadIdx := strings.Index(got, "hw.dPad")
	heapIdx := strings.Index(got, "vm.heapSize")
	if !(backIdx < dpadIdx && dpadIdx < heapIdx) {
		t.Errorf("appended keys are not sorted\ngot:\n%s", got)
	}
}

func TestRenderConfigIni_IsDeterministic(t *testing.T) {
	original := strings.Split("a.b=1\nc.d=2\n", "\n")
	kv := map[string]string{"a.b": "9", "c.d": "8", "e.f": "7", "g.h": "6"}

	first := renderConfigIni(original, kv)
	for i := 0; i < 50; i++ {
		if got := renderConfigIni(original, kv); got != first {
			t.Fatalf("output varies between runs\nfirst:\n%s\ngot:\n%s", first, got)
		}
	}
}

func TestRenderConfigIni_NoTrailingBlankLineGrowth(t *testing.T) {
	// Repeated tuning must not accumulate blank lines at the end of the file.
	kv := map[string]string{"hw.ramSize": "1024"}
	out := renderConfigIni(strings.Split("hw.ramSize=4096\n", "\n"), kv)
	for i := 0; i < 5; i++ {
		out = renderConfigIni(strings.Split(out, "\n"), kv)
	}
	if strings.HasSuffix(out, "\n\n") {
		t.Errorf("blank lines accumulated at EOF: %q", out)
	}
}
